### ISSUE TITLE
MVPレビュー

### ISSUE THREAD

**Issue by kenchasonakai** [naopon-hamumu/stamp_app#48]
LGTMです！
下記にレビュー内容記載しておりますのでご確認ください。
また、下記レビュー内容等を加味した本リリースの予定日をコメントで返信お願いいたします。

## レビュー
MVPリリースお疲れ様でした、下記の視点をもとにレビューいたします。

1. READMEから課題解決する実装がされているか&動いている
2. 静的コードチェックが入っている
3. 就活において十分な技術力を示せる機能を実装しているか
4. UIでユーザーが迷わないような導線を作れているか・ユーザーが使いたくなるようなサービス設計ができているか

### READMEから課題解決する実装がされているか&動いている
READMEに記載の機能はしっかりと実装されていそうですね

### 静的コードチェックが入っている
rubocop導入してしっかりチェックしていますね！
rubocopのデフォルトの設定だと余計なところまで指摘されることがあるので設定ファイルを追加してカスタマイズしてあげると良いかと思います。

### 就活において十分な技術力を示せる機能を実装しているか
GoogleMapやGeolocation APIなどをしっかりと使えていて良いですね

本リリースに追加予定の以下の機能を引き続き実装していきましょう
- タグ機能
- スタンプラリーのタグ機能
- スタンプラリーの検索機能（indexのタブごと）
- スタンプ集のページネーション
- 参加したスタンプラリーからのレコメンド機能
- RSpecの現在読んでいる本が終わり次第、テストを作成する
- OGPの追加
- パスワードリセット機能

### 下記にその他気になった点を挙げておいたので、ご確認ください。
画像に関して、Herokuを使っているとアップロードした画像が一定期間経過後勝手に消されてしまうのでS3などの外部ストレージを使用するようにしましょう。
せっかく使ってくれたユーザーの画像が消えてしまうの&画像のリンクが切れていると就活での印象も悪いので早急に対応した方が良いかと思います。

テストに関して、今後テストを書いていくかと思いますが、現状中身のないテストファイルが大量に存在しているので後々きちんと整理しておきましょう。

.DS_Storeのようなファイルがgit管理されてしまっているのでコミット前に確認する癖をつけておいた方が良いかと思います。必要ないファイルは削除しておきましょう。

**Comment by naopon-hamumu** [comment]
お忙しい中、ありがとうございます！
本リリースの予定日は10/20(金)を現段階では考えております。
また、不必要なファイルを削除しておきます。

画像の保存はHerokuからS３にすでに移行済みです。

重ねてありがとうございました！

**Comment by kenchasonakai** [comment]
ご返信ありがとうございます！

本リリース日とS3の件承知しました 🙆‍♂️

**Comment by naopon-hamumu** [comment]
お忙しい中、誠にありがとうございます！！🐹
